### ISSUE TITLE
优化Buffer的clear方法，避免大量的for循环？

### ISSUE THREAD

**Issue by huanghantao** [fswo/rfc#8]
目前，我们`Buffer`类的`clear`方法是直接把`length`的数据清空为`0`，或许，我们可以用几个标志来假设数据被清空了？这样就可以避免`for`循环。

**Comment by huanghantao** [comment]
对比一下优化后的代码，`HTTP Server`的性能有没有提升。

**Comment by yangclsir** [comment]
我的思路是这样的：
1.首先给Buffer类定义一个private size_t _offset属性
2.每次clear时，length = 0;offset += length;
3.每次调用append()方法时，memcpy(_buffer + _offset + _length, str, length);

疑问：
1.Buffer::size()返回的大小是含有_offset大小的，所以随着append()会越来越小，但是给使用者的感觉是虽然每次都clear()了，但是size()却不够用了?

**Comment by huanghantao** [comment]
> 我的思路是这样的：
> 1.首先给Buffer类定义一个private size_t _offset属性
> 2.每次clear时，length = 0;offset += length;
> 3.每次调用append()方法时，memcpy(_buffer + _offset + _length, str, length);
> 
> 疑问：
> 1.Buffer::size()返回的大小是含有_offset大小的，所以随着append()会越来越小，但是给使用者的感觉是虽然每次都clear()了，但是size()却不够用了?

这个`offset`看起来是可以不需要的。

**Comment by huanghantao** [comment]
@yangclsir 
除非后面，我们需要往指定位置`read`或者`write` `buffer`，这个`offset`是有用的。

**Comment by yangclsir** [comment]
> @yangclsir
> 除非以后我们需要往指定位置`read`或者`write` `buffer`，这个`offset`是有用的。

明白了，彻底明白
